cranelift/isle: fix broken broken tests (#78)
Updates some of the "broken" test cases to ensure they have full enum types.

These were failing with errors such as:

```
---- test_broken_iadd_shift2 stdout ----
Verifying iadd rules in file: ./examples/broken/iadd/broken_shift2.isle
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cranelift/isle/veri/veri_engine/src/annotations.rs:322:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'test_broken_iadd_shift2' panicked at 'called `Result::unwrap()` on an `Err` value: Error { error: "Test thread panicked Any { .. }", total_delay: 0ns, tries: 1 }', cranelift/isle/veri/veri_engine/tests/utils/mod.rs:109:12
```

Following the change in #73, we now error if an enum model does not have a corresponding type declaration. This PR fixes the problem by adding full enum type declarations alongside the models.